language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "trona85-github"
    token:
      secure: "8adc4684193cfe1cd21a86da59c789a0bd515032"
    branches:
      - master
jdk:
  - oraclejdk8
script:
  - ./gradlew assemble
  - ./gradlew sonarqube
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'


