package test;
//import org.junit.Test;
//import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'oscar' at '16/10/17 15:41' with Gradle 2.14.1
 *
 * @author oscar, @date 16/10/17 15:41
 */
/*public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}*/
